In [1]:
pip install kaggle

Requirement already satisfied: kaggle in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (2.2.1)
Requirement already satisfied: bleach in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from kaggle) (6.2.0)
Requirement already satisfied: jupytext in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from kaggle) (1.19.3)
Requirement already satisfied: kagglesdk<1.0,>=0.1.27 in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from kaggle) (0.1.28)
Requirement already satisfied: packaging in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from kaggle) (25.0)
Requirement already satisfied: protobuf in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from kaggle) (6.32.0)
Requirement already satisfied: python-dateutil in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-dotenv in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from kaggle) (1.2.2)
Requirement already satisfied: python-slugify in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from kaggle) (2.6.3)
Requirement already satisfied: webencodings in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from jupytext->kaggle) (6.0.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from nbformat->jupytext->kaggle) (2.21.1)
Requirement already satisfied: jsonschema>=2.6 in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from nbformat->jupytext->kaggle) (4.25.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from nbformat->jupytext->kaggle) (5.8.1)
Requirement already satisfied: traitlets>=5.1 in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from nbformat->jupytext->kaggle) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.4.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.26.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.3.8)
Requirement already satisfied: pywin32>=300 in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (311)
Requirement already satisfied: typing-extensions>=4.4.0 in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.15.0)
Requirement already satisfied: six>=1.5 in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from requests->kaggle) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from requests->kaggle) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from requests->kaggle) (2026.1.4)
Requirement already satisfied: colorama in c:\users\vishwa\.conda\envs\batch433\lib\site-packages (from tqdm->kaggle) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
import numpy as np
import sklearn
import nltk
import re

In [2]:
df  = pd.read_csv(r"C:\Users\vishwa\Downloads\Reviews_50k.csv")

In [3]:
df

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
1,8,B006K2ZZ7K,A3JRGQVEQN31IQ,Pamela G. Williams,0,0,5,1336003200,"Wonderful, tasty taffy",This taffy is so good. It is very soft and ch...
2,25,B001GVISJM,A22P2J09NJ9HKE,"S. Cabanaugh ""jilly pepper""",0,0,5,1295481600,Please sell these in Mexico!!,"I have lived out of the US for over 7 yrs now,..."
3,32,B003F6UO7K,A31OQO709M20Y7,"Molly V. Smith ""staral""",0,1,5,1288310400,THIS IS MY TASTE...,"This offer is a great price and a great taste,..."
4,53,B000G6RPMY,A9L6L5H9BPEBO,Edwin C. Pauzer,1,1,4,1348876800,You'll go nuts over Ass-Kickin' Peanuts.,This wasn't in stock the last time I looked. I...
...,...,...,...,...,...,...,...,...,...,...
49995,568396,B001EQ5O6Y,A2NEOGFAJDJMFV,SUZANNE L. ARASIM,0,0,5,1279411200,"Very handy, yummy too",My mom-in-law had rec'd 1 box of these in a gi...
49996,568409,B0018CLWM4,AJGOF4W50ZNB4,je2u,3,3,5,1310515200,Premium Edge Kitten Food,This is a good food with decent ingredients & ...
49997,568421,B004BY23I8,A2B07RJZVDUJA5,P. Mase,0,0,4,1350518400,Co-co-yummy!,Love the coconut flavor of this tea. Two thin...
49998,568425,B001FPT1WM,A291HTT117RVS9,"MadisonVeggie ""Lynette in Wisconsin""",2,2,5,1333411200,"Unusual, even for a violet candy",I've tried several violet flavored candies in ...
49999,568446,B001EO7N10,A2E5C8TTAED4CQ,S. Linkletter,2,2,5,1268006400,Five Spice Powder,"You can make this mix yourself, but the Star A..."

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Id                      50000 non-null  int64
 1   ProductId               50000 non-null  object
 2   UserId                  50000 non-null  object
 3   ProfileName             50000 non-null  object
 4   HelpfulnessNumerator    50000 non-null  int64
 5   HelpfulnessDenominator  50000 non-null  int64
 6   Score                   50000 non-null  int64
 7   Time                    50000 non-null  int64
 8   Summary                 49999 non-null  object
 9   Text                    50000 non-null  object
dtypes: int64(5), object(5)
memory usage: 3.8+ MB

In [5]:
df['Summary'].fillna("unknown")

0                           "Delight" says it all
1                          Wonderful, tasty taffy
2                   Please sell these in Mexico!!
3                             THIS IS MY TASTE...
4        You'll go nuts over Ass-Kickin' Peanuts.
                           ...
49995                       Very handy, yummy too
49996                    Premium Edge Kitten Food
49997                                Co-co-yummy!
49998            Unusual, even for a violet candy
49999                           Five Spice Powder
Name: Summary, Length: 50000, dtype: object

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Id                      50000 non-null  int64
 1   ProductId               50000 non-null  object
 2   UserId                  50000 non-null  object
 3   ProfileName             50000 non-null  object
 4   HelpfulnessNumerator    50000 non-null  int64
 5   HelpfulnessDenominator  50000 non-null  int64
 6   Score                   50000 non-null  int64
 7   Time                    50000 non-null  int64
 8   Summary                 49999 non-null  object
 9   Text                    50000 non-null  object
dtypes: int64(5), object(5)
memory usage: 3.8+ MB

In [7]:
for i in df:
    print("*"*10,i,"*"*10)
    print()
    print(df[i].unique())
    print()

********** Id **********

[     3      8     25 ... 568421 568425 568446]

********** ProductId **********

['B000LQOCH0' 'B006K2ZZ7K' 'B001GVISJM' ... 'B004BY23I8' 'B001FPT1WM'
 'B001EO7N10']

********** UserId **********

['ABXLMWJIXXAIN' 'A3JRGQVEQN31IQ' 'A22P2J09NJ9HKE' ... 'AJGOF4W50ZNB4'
 'A2B07RJZVDUJA5' 'A2E5C8TTAED4CQ']

********** ProfileName **********

['Natalia Corres "Natalia Corres"' 'Pamela G. Williams'
 'S. Cabanaugh "jilly pepper"' ... 'je2u' 'P. Mase' 'S. Linkletter']

********** HelpfulnessNumerator **********

[  1   0   4  17   2  14  20   3  11   8  15   5  16   7   6  13  12  10
  70   9  23  19  97  82  25 149  66  38  26  22  51 135 157  32  44  24
  31  30  45 112  21  42  62  33  40  54  36  28  18  29 286  64  75  52
  27  35 125  49  48 232  88  37  67  78  69  80 189  41  84 142  56  68
  59 110  55  73  91  58  39 107 119  43  99 117  34  72 138  85 319  46
 170 105 454 439 274  76  47  50 205  65 137 166 123  83 115  60 143  71
 151 100  53 111  77 321  79 122]

********** HelpfulnessDenominator **********

[  1   0   5  19   4   2   3  17  27  11   6  12  18   7  14   9  24  15
  20  13  36  74   8  25  22  21  10 100  84  26 155  23  66  41  40  53
 135 170  35  51  16  44  48  30  52 120  49  63  33  56  28  70  45  37
  29  31 307  77 137  55  71 235  88  32  34  72  75  80  47  46  83  42
 216  50  59  38 159  57  69  61 110  39  79  98  85 119  64 115 174 150
  43  68  82 149 126  54 323 171 108 462 452 284  78  87  62 229 163 172
 139 117 152  81 160 112 143 106  91 104  92 322 130  73  89 124]

********** Score **********

[4 5 3 1 2]

********** Time **********

[1219017600 1336003200 1295481600 ... 1137456000 1144972800 1118707200]

********** Summary **********

['"Delight" says it all' 'Wonderful, tasty taffy'
 'Please sell these in Mexico!!' ... 'Co-co-yummy!'
 'Unusual, even for a violet candy' 'Five Spice Powder']

********** Text **********

['This is a confection that has been around a few centuries.  It is a light, pillowy citrus gelatin with nuts - in this case Filberts. And it is cut into tiny squares and then liberally coated with powdered sugar.  And it is a tiny mouthful of heaven.  Not too chewy, and very flavorful.  I highly recommend this yummy treat.  If you are familiar with the story of C.S. Lewis\' "The Lion, The Witch, and The Wardrobe" - this is the treat that seduces Edmund into selling out his Brother and Sisters to the Witch.'
 'This taffy is so good.  It is very soft and chewy.  The flavors are amazing.  I would definitely recommend you buying it.  Very satisfying!!'
 "I have lived out of the US for over 7 yrs now, and I so miss my Twizzlers!!  When I go back to visit or someone visits me, I always stock up.  All I can say is YUM!<br />Sell these in Mexico and you will have a faithful buyer, more often than I'm able to buy them right now."
 ...
 'Love the coconut flavor of this tea.  Two things I wish were different-the metal rim is slightly sharp and you need to be careful, would prefer that they make this in larger size (at least 16 oz).'
 'I\'ve tried several violet flavored candies in the past, and this is my favorite. Along with the floral flavor/aroma, it also has a nice citrus undertone which complements it well. Expensive, but hard candies last a long time, unless you "chain suck" them like I sometimes do!'
 'You can make this mix yourself, but the Star Anise is often difficult to find.  Usually I use this mix to make Oriental-style pork or chicken dishes, but today I added a little to some fish boiled with lemon juice and black pepper.  It was very good without being actually Oriental in overall impression.']

In [8]:
for i in df:
    print("*"*10,i,"*"*10)
    print()
    print(df[i].value_counts())
    print()

********** Id **********

Id
3         1
8         1
25        1
32        1
53        1
         ..
568396    1
568409    1
568421    1
568425    1
568446    1
Name: count, Length: 50000, dtype: int64

********** ProductId **********

ProductId
B007JFMH8M    84
B003B3OOPA    73
B0026RQTGE    67
B002QWHJOU    60
B000NMJWZO    57
              ..
B0002G3UWM     1
B003EMXLU2     1
B006Z0Z6WG     1
B000YCQH4W     1
B007B9J6G2     1
Name: count, Length: 20718, dtype: int64

********** UserId **********

UserId
A1YUL9PCJR3JTY    45
AY12DBB0U420B     40
A281NPSIMI1C2R    36
A3OXHLG6DIBRW8    34
A3TVZM3ZIXG8YW    25
                  ..
A25ZSDXJ9KUA6W     1
A1AR9L2VDNVQH0     1
ACWT094KA1SFE      1
AXDJ9KF74MOYP      1
A24E0CIZBWMO4L     1
Name: count, Length: 40325, dtype: int64

********** ProfileName **********

ProfileName
O. Brown "Ms. O. Khannah-Brown"           45
Gary Peterson                             40
Rebecca of Amazon "The Rebecca Review"    36
C. F. Hill "CFH"                          34
Steve                                     26
                                          ..
S. Cabanaugh "jilly pepper"                1
Pamela G. Williams                         1
Natalia Corres "Natalia Corres"            1
S. Linkletter                              1
Deanna O. Dowell "Dee"                     1
Name: count, Length: 37292, dtype: int64

********** HelpfulnessNumerator **********

HelpfulnessNumerator
0      26729
1      10300
2       4735
3       2529
4       1492
       ...
151        1
77         1
321        1
79         1
122        1
Name: count, Length: 116, dtype: int64

********** HelpfulnessDenominator **********

HelpfulnessDenominator
0      23737
1       9971
2       5467
3       2933
4       1937
       ...
104        1
322        1
92         1
130        1
89         1
Name: count, Length: 124, dtype: int64

********** Score **********

Score
5    32097
4     7008
1     4528
3     3791
2     2576
Name: count, dtype: int64

********** Time **********

Time
1350345600    104
1351036800     98
1347062400     95
1346889600     94
1344211200     91
             ...
1057104000      1
1108512000      1
1137456000      1
1144972800      1
1118707200      1
Name: count, Length: 2503, dtype: int64

********** Summary **********

Summary
Delicious!                          216
Delicious                           205
Yummy!                              143
Yummy                               123
Great product                       103
                                   ...
Very handy, yummy too                 1
Premium Edge Kitten Food              1
Co-co-yummy!                          1
Unusual, even for a violet candy      1
Authentic Thai curry                  1
Name: count, Length: 39107, dtype: int64

********** Text **********

Text
This review will make me sound really stupid, but whatever. I don't really care as long as people find out what's real and can avoid my mistakes.<br /><br />I got my wonderful little sweet Bella Bean when she was a few days shy of three years old. She had been bounced around from house to house and eating whatever was cheap. I have had cats around me my entire life, for about twenty-five years now. My mother always just fed them whatever, the kinds of food you buy in the supermarket - Friskies, Nine Lives, Kit & Kaboodle, stuff like that. And our cats were always fine, at least in terms of their eating habits. They would eat in the morning, stop when they were done, come back, and eat some more when they got hungry.<br /><br />My housemate at the time was working for Hill's and assured me that this was the best food ever made, so great, so on and so forth. I now know that she is an utter buffoon, but I initially trusted her judgment, which is so unfortunate because she doesn't think. She also had plenty of coupons for free or deeply discounted bags, which made it a much more attractive choice.<br /><br />I first tried feeding the little Bean an unmeasured amount of Science Diet in a bowl, but that didn't work, as she would devour it in one sitting. So then I took to measuring it, and she did the same thing. Then I started parsing it out to twice a day. That didn't work either, because she would start going crazy in the middle of the day, running around, intentionally destroying things, deliberately spilling her water, crying, etc., until she got more food. So then I split it into three servings. Same thing. Then it got to be four servings. That was a little better, but it was too much maintenance and unrealistic to be around every day to feed her four times. So then it went back to three. All the while, I was trying to reduce the amount of food I was feeding her to less than 3/4 of a cup because she was a little chubby. Reducing was hell. She became even more hungry, but I figured she would get used to it. Not really.<br /><br />For over a year, she would wake me up every morning looking for food in a serious way, knocking things off my desk, ripping up any paper she could find, scratching at the door and committing general acts of mischief. As soon as she got food, she was back to her sweet self, but only for three or four hours.<br /><br />We thought she was bored, we thought she was a little nutty, and maybe even had a kitty eating disorder. She always wanted food. It was kind of funny but in the end it was just sad.<br /><br />A few weeks back, we took her to a new (good, non-money factory) vet for her second checkup since I've had her. I talked with him about her being always hungry. He asked what she ate, and I told him the adult indoor Science Diet. Without saying as much, he basically told me that this food is garbage and I should look for something else. He said cat food should have a protein followed by a carbohydrate as the first two ingredients. Science Diet does, in a very loose, by-product kind of way - ground up slaughterhouse leftovers and corn dust. Then they put a bunch of vitamins in it to make it "healthy," instead of just using good ingredients from the beginning. Not that I care about spending money on the Bean, but this food is way too expensive for what it is.<br /><br />So we began transitioning her onto Wellness indoor formula about two weeks ago. She is still eating 50 percent Science Diet with 50 percent Wellness (you really shouldn't just give a cat different food one day out of the blue) but SHE NEVER FREAKS OUT ANYMORE. It's amazing. And it's 100 percent because she is eating real food now, along with that sawdust and chicken hearts I still regrettable have to feed her. We have her down to eating twice a day, only 1/3 cup in TOTAL. She was eating three times a day, 5/8 of a cup in total. Now she eats some in the morning, walks away, eats some more a few hours later, and then looks for dinner about twelve hours after her initial feeding. No more knocking things over, no more trashing Dad's papers on the desk, no more howling, no more deliberately spilled water on the floor. It's incredible.<br /><br />I feel so bad that I was doing this to her for so long. We really thought she was just being dramatic or whatever. But no, she was genuinely hungry because she wasn't eating any real food.<br /><br />Do your cat a favor - buy her or him so food made with real ingredients, things you would eat - Wellness, Halo, Innova, Evo, whatever. Figure it out for yourself, but please don't feed your cat this. It's garbage.    25
Diamond Almonds<br />Almonds are a good source of magnesium. One ounce contain approximately 20% of the RDA for an adult recommended dietary allowance (RDA)<br />Recommended Dietary Allowance (RDA) the amounts of selected nutrients considered adequate to meet the known nutrient needs of healthy people. The RDA is based on scientific knowledge and has been presented by a committee of the Food and Nutrition Board (FNB) of the National Academy of Sciences (NAS). The Canadian equivalent is the Recommended Nutrient Intakes. RDA is generally accepted throughout the world as a valid source of information. At least 40 different nations have as well as organizations have published standards similar to the RDA.<br /><br />Magnesium is the fourth most abundant mineral in the body and is essential to good health. Approximately 50% of total body magnesium is found in bone. The other half is found predominantly inside cells of body tissues and organs. Only 1% of magnesium is found in blood, but the body works very hard to keep blood levels of magnesium constant.<br />Magnesium is needed for more than 300 biochemical reactions in the body. It helps maintain normal muscle and nerve function, keeps heart rhythm steady, supports a healthy immune system, and keeps bones strong. Magnesium also helps regulate blood sugar levels, promotes normal blood pressure, and is known to be involved in energy metabolism and protein synthesis. There is an increased interest in the role of magnesium in preventing and managing disorders such as hypertension, cardiovascular disease, and diabetes. Dietary magnesium is absorbed in the small intestines. Are you taking enough magnesium in the diet? The recommended daily allowance is 300mgs/day for men, 350mgs for women. Magnesium is extremely safe by mouth - too much simply causes diarrhea. Try increasing the amount of magnesium you take by mouth until it causes diarrhea, then reduce the dose slightly so it does not. This is called taking magnesium to bowel tolerance (just like using vitamin C to bowel tolerance.<br /><br />Almonds are a good source of Fiber.<br />One ounce contains approximately 12% of the RDA for an adult.<br />So, in summary, Almonds are a very healthy snack, so what's left to say?<br /><br />Two things:<br />1st be cautious about "bowel tolerance" or "happy bowels" if you prefer.<br />2nd Taste.  I realize that taste is a personal thing.  That's why they make chocolate, strawberry, and vanilla.<br /><br />Here's my current favorites"<br /><br /> 1st Blue Diamond Dark mint dark chocolate (reminds me of the chocolate mint Girl Scout Cookies with less sugar).<br /><br />2nd Blue diamond Dark Chocolate Oven Roasted<br />3rd  Blue diamond Blue Butter Toffee<br />4thd Blue Diamond Almonds Bold Habanero BBQ (reminds me of  BBQ potato chips again with less sugar).<br />5th Bold Blazin Buffalo Wing<br />6th Blue Diamond Almonds Cinnamon Brown Sugar<br />7th  Blue Diamond Almonds Lime `n Chili<br />8th  Blue Diamond Almonds Smokehouse<br />9th  Bold Wasabi & Soy Sauce<br /><br />But that's just me: you might have a completely different take on these flavors.<br /> 4th  and 5th are very close.<br /><br />Gunner<br />May, 2012                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               13
I have two cats, one 6 and one 2 years old. Both are indoor cats in excellent health. I saw the negative review and talked to my vet about it. I've also asked a number of veterinary professionals what to feed my cats and they all answer the same thing: Science Diet. Sure, you'll see stories of how one person's cat had issues, but even if that's 100% true, it's 1 case out of millions. Science and fact aren't based on someone's experience.<br /><br />So my point is, I love my cats and I'm very concerned about their health. I trust people who actually have medical degrees and experience with a wide range of animals. My only caution is do not fall for some hype or scare tactic that recommends some unproven or untested food or some fad diet for your pet. Don't listen to me, don't listen to the negative review. ASK YOUR VET what they recommend, and follow their instructions. My guess is you'll end up buying the Science Diet anyhow.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        8

In [9]:
df["Summary"]=df["Summary"].astype('string')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Id                      50000 non-null  int64
 1   ProductId               50000 non-null  object
 2   UserId                  50000 non-null  object
 3   ProfileName             50000 non-null  object
 4   HelpfulnessNumerator    50000 non-null  int64
 5   HelpfulnessDenominator  50000 non-null  int64
 6   Score                   50000 non-null  int64
 7   Time                    50000 non-null  int64
 8   Summary                 49999 non-null  string
 9   Text                    50000 non-null  object
dtypes: int64(5), object(4), string(1)
memory usage: 3.8+ MB

In [11]:
df["clean_summary"] = df["Summary"].fillna("").str.lower()

In [12]:
df["clean_summary"] = df["Summary"].astype(str).str.lower()

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Id                      50000 non-null  int64
 1   ProductId               50000 non-null  object
 2   UserId                  50000 non-null  object
 3   ProfileName             50000 non-null  object
 4   HelpfulnessNumerator    50000 non-null  int64
 5   HelpfulnessDenominator  50000 non-null  int64
 6   Score                   50000 non-null  int64
 7   Time                    50000 non-null  int64
 8   Summary                 49999 non-null  string
 9   Text                    50000 non-null  object
 10  clean_summary           50000 non-null  object
dtypes: int64(5), object(5), string(1)
memory usage: 4.2+ MB

In [14]:
df["clean_summary"] = df["clean_summary"].apply(lambda x: re.sub(r'[^a-z0-9\s]+', ' ', x))

In [15]:
from nltk.stem import WordNetLemmatizer
le = WordNetLemmatizer()
df["clean_summary"] = df["clean_summary"].apply(lambda x: le.lemmatize(x))

In [16]:
df["clean_summary"]

0                            delight  says it all
1                          wonderful  tasty taffy
2                    please sell these in mexico
3                               this is my taste
4        you ll go nuts over ass kickin  peanuts
                           ...
49995                       very handy  yummy too
49996                    premium edge kitten food
49997                                co co yummy
49998            unusual  even for a violet candy
49999                           five spice powder
Name: clean_summary, Length: 50000, dtype: object

In [17]:
from nltk.corpus import stopwords

stop_words = stopwords.words('english')

In [18]:
df["clean_summary"] = df["clean_summary"].apply(lambda a : a.split())

In [19]:
df

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text,clean_summary
0,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...,"[delight, says, it, all]"
1,8,B006K2ZZ7K,A3JRGQVEQN31IQ,Pamela G. Williams,0,0,5,1336003200,"Wonderful, tasty taffy",This taffy is so good. It is very soft and ch...,"[wonderful, tasty, taffy]"
2,25,B001GVISJM,A22P2J09NJ9HKE,"S. Cabanaugh ""jilly pepper""",0,0,5,1295481600,Please sell these in Mexico!!,"I have lived out of the US for over 7 yrs now,...","[please, sell, these, in, mexico]"
3,32,B003F6UO7K,A31OQO709M20Y7,"Molly V. Smith ""staral""",0,1,5,1288310400,THIS IS MY TASTE...,"This offer is a great price and a great taste,...","[this, is, my, taste]"
4,53,B000G6RPMY,A9L6L5H9BPEBO,Edwin C. Pauzer,1,1,4,1348876800,You'll go nuts over Ass-Kickin' Peanuts.,This wasn't in stock the last time I looked. I...,"[you, ll, go, nuts, over, ass, kickin, peanuts]"
...,...,...,...,...,...,...,...,...,...,...,...
49995,568396,B001EQ5O6Y,A2NEOGFAJDJMFV,SUZANNE L. ARASIM,0,0,5,1279411200,"Very handy, yummy too",My mom-in-law had rec'd 1 box of these in a gi...,"[very, handy, yummy, too]"
49996,568409,B0018CLWM4,AJGOF4W50ZNB4,je2u,3,3,5,1310515200,Premium Edge Kitten Food,This is a good food with decent ingredients & ...,"[premium, edge, kitten, food]"
49997,568421,B004BY23I8,A2B07RJZVDUJA5,P. Mase,0,0,4,1350518400,Co-co-yummy!,Love the coconut flavor of this tea. Two thin...,"[co, co, yummy]"
49998,568425,B001FPT1WM,A291HTT117RVS9,"MadisonVeggie ""Lynette in Wisconsin""",2,2,5,1333411200,"Unusual, even for a violet candy",I've tried several violet flavored candies in ...,"[unusual, even, for, a, violet, candy]"
49999,568446,B001EO7N10,A2E5C8TTAED4CQ,S. Linkletter,2,2,5,1268006400,Five Spice Powder,"You can make this mix yourself, but the Star A...","[five, spice, powder]"

In [20]:
df["clean_summary"] = df["clean_summary"].apply(
    lambda words: [word for word in words if word not in stop_words]
)

In [21]:
df

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text,clean_summary
0,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...,"[delight, says]"
1,8,B006K2ZZ7K,A3JRGQVEQN31IQ,Pamela G. Williams,0,0,5,1336003200,"Wonderful, tasty taffy",This taffy is so good. It is very soft and ch...,"[wonderful, tasty, taffy]"
2,25,B001GVISJM,A22P2J09NJ9HKE,"S. Cabanaugh ""jilly pepper""",0,0,5,1295481600,Please sell these in Mexico!!,"I have lived out of the US for over 7 yrs now,...","[please, sell, mexico]"
3,32,B003F6UO7K,A31OQO709M20Y7,"Molly V. Smith ""staral""",0,1,5,1288310400,THIS IS MY TASTE...,"This offer is a great price and a great taste,...",[taste]
4,53,B000G6RPMY,A9L6L5H9BPEBO,Edwin C. Pauzer,1,1,4,1348876800,You'll go nuts over Ass-Kickin' Peanuts.,This wasn't in stock the last time I looked. I...,"[go, nuts, ass, kickin, peanuts]"
...,...,...,...,...,...,...,...,...,...,...,...
49995,568396,B001EQ5O6Y,A2NEOGFAJDJMFV,SUZANNE L. ARASIM,0,0,5,1279411200,"Very handy, yummy too",My mom-in-law had rec'd 1 box of these in a gi...,"[handy, yummy]"
49996,568409,B0018CLWM4,AJGOF4W50ZNB4,je2u,3,3,5,1310515200,Premium Edge Kitten Food,This is a good food with decent ingredients & ...,"[premium, edge, kitten, food]"
49997,568421,B004BY23I8,A2B07RJZVDUJA5,P. Mase,0,0,4,1350518400,Co-co-yummy!,Love the coconut flavor of this tea. Two thin...,"[co, co, yummy]"
49998,568425,B001FPT1WM,A291HTT117RVS9,"MadisonVeggie ""Lynette in Wisconsin""",2,2,5,1333411200,"Unusual, even for a violet candy",I've tried several violet flavored candies in ...,"[unusual, even, violet, candy]"
49999,568446,B001EO7N10,A2E5C8TTAED4CQ,S. Linkletter,2,2,5,1268006400,Five Spice Powder,"You can make this mix yourself, but the Star A...","[five, spice, powder]"

In [22]:
df["cleaned_text"] = df["Text"].apply(lambda a : a.lower())

In [23]:
df["cleaned_text"]

0        this is a confection that has been around a fe...
1        this taffy is so good.  it is very soft and ch...
2        i have lived out of the us for over 7 yrs now,...
3        this offer is a great price and a great taste,...
4        this wasn't in stock the last time i looked. i...
                               ...
49995    my mom-in-law had rec'd 1 box of these in a gi...
49996    this is a good food with decent ingredients & ...
49997    love the coconut flavor of this tea.  two thin...
49998    i've tried several violet flavored candies in ...
49999    you can make this mix yourself, but the star a...
Name: cleaned_text, Length: 50000, dtype: object

In [24]:
df["cleaned_text"] = df["cleaned_text"].apply(lambda x: re.sub(r'[^a-z0-9\s]+', ' ', x))

In [25]:
df["cleaned_text"]

0        this is a confection that has been around a fe...
1        this taffy is so good   it is very soft and ch...
2        i have lived out of the us for over 7 yrs now ...
3        this offer is a great price and a great taste ...
4        this wasn t in stock the last time i looked  i...
                               ...
49995    my mom in law had rec d 1 box of these in a gi...
49996    this is a good food with decent ingredients   ...
49997    love the coconut flavor of this tea   two thin...
49998    i ve tried several violet flavored candies in ...
49999    you can make this mix yourself  but the star a...
Name: cleaned_text, Length: 50000, dtype: object

In [26]:
from nltk.stem import WordNetLemmatizer
le = WordNetLemmatizer()
df["cleaned_text"] = df["cleaned_text"].apply(lambda x: le.lemmatize(x))

In [27]:
df["cleaned_text"]

0        this is a confection that has been around a fe...
1        this taffy is so good   it is very soft and ch...
2        i have lived out of the us for over 7 yrs now ...
3        this offer is a great price and a great taste ...
4        this wasn t in stock the last time i looked  i...
                               ...
49995    my mom in law had rec d 1 box of these in a gi...
49996    this is a good food with decent ingredients   ...
49997    love the coconut flavor of this tea   two thin...
49998    i ve tried several violet flavored candies in ...
49999    you can make this mix yourself  but the star a...
Name: cleaned_text, Length: 50000, dtype: object

df["cleaned_text"] = df["Text"].apply(lambda a : a.split())

In [28]:
from nltk.tokenize import sent_tokenize

df["cleaned_text"] = df["cleaned_text"].apply(
    lambda x: sent_tokenize(str(x))
)

In [29]:
df["cleaned_text"]

0        [this is a confection that has been around a f...
1        [this taffy is so good   it is very soft and c...
2        [i have lived out of the us for over 7 yrs now...
3        [this offer is a great price and a great taste...
4        [this wasn t in stock the last time i looked  ...
                               ...
49995    [my mom in law had rec d 1 box of these in a g...
49996    [this is a good food with decent ingredients  ...
49997    [love the coconut flavor of this tea   two thi...
49998    [i ve tried several violet flavored candies in...
49999    [you can make this mix yourself  but the star ...
Name: cleaned_text, Length: 50000, dtype: object

In [30]:
df

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text,clean_summary,cleaned_text
0,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...,"[delight, says]",[this is a confection that has been around a f...
1,8,B006K2ZZ7K,A3JRGQVEQN31IQ,Pamela G. Williams,0,0,5,1336003200,"Wonderful, tasty taffy",This taffy is so good. It is very soft and ch...,"[wonderful, tasty, taffy]",[this taffy is so good it is very soft and c...
2,25,B001GVISJM,A22P2J09NJ9HKE,"S. Cabanaugh ""jilly pepper""",0,0,5,1295481600,Please sell these in Mexico!!,"I have lived out of the US for over 7 yrs now,...","[please, sell, mexico]",[i have lived out of the us for over 7 yrs now...
3,32,B003F6UO7K,A31OQO709M20Y7,"Molly V. Smith ""staral""",0,1,5,1288310400,THIS IS MY TASTE...,"This offer is a great price and a great taste,...",[taste],[this offer is a great price and a great taste...
4,53,B000G6RPMY,A9L6L5H9BPEBO,Edwin C. Pauzer,1,1,4,1348876800,You'll go nuts over Ass-Kickin' Peanuts.,This wasn't in stock the last time I looked. I...,"[go, nuts, ass, kickin, peanuts]",[this wasn t in stock the last time i looked ...
...,...,...,...,...,...,...,...,...,...,...,...,...
49995,568396,B001EQ5O6Y,A2NEOGFAJDJMFV,SUZANNE L. ARASIM,0,0,5,1279411200,"Very handy, yummy too",My mom-in-law had rec'd 1 box of these in a gi...,"[handy, yummy]",[my mom in law had rec d 1 box of these in a g...
49996,568409,B0018CLWM4,AJGOF4W50ZNB4,je2u,3,3,5,1310515200,Premium Edge Kitten Food,This is a good food with decent ingredients & ...,"[premium, edge, kitten, food]",[this is a good food with decent ingredients ...
49997,568421,B004BY23I8,A2B07RJZVDUJA5,P. Mase,0,0,4,1350518400,Co-co-yummy!,Love the coconut flavor of this tea. Two thin...,"[co, co, yummy]",[love the coconut flavor of this tea two thi...
49998,568425,B001FPT1WM,A291HTT117RVS9,"MadisonVeggie ""Lynette in Wisconsin""",2,2,5,1333411200,"Unusual, even for a violet candy",I've tried several violet flavored candies in ...,"[unusual, even, violet, candy]",[i ve tried several violet flavored candies in...
49999,568446,B001EO7N10,A2E5C8TTAED4CQ,S. Linkletter,2,2,5,1268006400,Five Spice Powder,"You can make this mix yourself, but the Star A...","[five, spice, powder]",[you can make this mix yourself but the star ...

from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

df["cleaned_text"] = df["cleaned_text"].apply(
    lambda x: (
        word.remove() for word in x
        if word not in stop_words
    )
)

df["cleaned_text"] = df["cleaned_text"].apply(
    lambda words: [word for word in words if word not in stop_words]
)

In [31]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

df["cleaned_text"] = df["cleaned_text"].apply(
    lambda x: [word for word in str(x).split() if word not in stop_words]
)

print(df["cleaned_text"].iloc[0])

["['this", 'confection', 'around', 'centuries', 'light', 'pillowy', 'citrus', 'gelatin', 'nuts', 'case', 'filberts', 'cut', 'tiny', 'squares', 'liberally', 'coated', 'powdered', 'sugar', 'tiny', 'mouthful', 'heaven', 'chewy', 'flavorful', 'highly', 'recommend', 'yummy', 'treat', 'familiar', 'story', 'c', 'lewis', 'lion', 'witch', 'wardrobe', 'treat', 'seduces', 'edmund', 'selling', 'brother', 'sisters', "witch']"]

In [32]:
df.head(2)

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text,clean_summary,cleaned_text
0,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...,"[delight, says]","[['this, confection, around, centuries, light,..."
1,8,B006K2ZZ7K,A3JRGQVEQN31IQ,Pamela G. Williams,0,0,5,1336003200,"Wonderful, tasty taffy",This taffy is so good. It is very soft and ch...,"[wonderful, tasty, taffy]","[['this, taffy, good, soft, chewy, flavors, am..."

In [33]:
X = df[['cleaned_text','clean_summary']]
y = df[['Score']]

In [34]:
for i in y:
    print(y[i].unique())

[4 5 3 1 2]

In [35]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.8,random_state=42)

In [36]:
X_train

,cleaned_text,clean_summary
39087,"[['i, switched, milk, found, local, supermarke...","[really, good, milk]"
30893,"[['i, used, product, recipe, easy, use, desser...","[wish, could, buy, locally]"
45278,"[['this, far, best, coffee, tried, far, least,...",[coffee]
16398,"[['if, like, strong, taste, coffee, dark, magi...","[great, taste]"
13653,"[['aside, digestive, issues, suffered, adult, ...","[pleased, far]"
...,...,...
11284,"[['2, yr, old, golden, retriever, loves, jerky...","[jas, loves, food, general, definitely, loves]"
44732,"[['so, accidentley, purchased, decided, give, ...","[horrible, taste]"
38158,"[['great, product, pre, fab, almost, good, rec...",[mcilhenny]
860,"[['i, bought, years, ago, walmart, br, stopped...","[great, taste]"
15795,"[['these, great, think, might, even, better, r...",[good]

In [37]:
from sklearn.feature_extraction.text import CountVectorizer
bow = CountVectorizer(max_features=5000)
X_train_trans = bow.fit_transform([" ".join(map(str, x)) for x in X_train["cleaned_text"]])
X_test_trans = bow.transform([" ".join(map(str, x)) for x in X_test["cleaned_text"]])

In [38]:
bow.get_feature_names_out()

array(['00', '000', '09', ..., 'ziploc', 'ziplock', 'zuke'],
      shape=(5000,), dtype=object)

In [39]:
X_train_trans

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 1261569 stored elements and shape (40000, 5000)>

In [40]:
X_test_trans

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 317678 stored elements and shape (10000, 5000)>

In [41]:
from sklearn.preprocessing import OrdinalEncoder
OE = OrdinalEncoder().set_output(transform="pandas")
y_train_trans = OE.fit_transform(y_train)

In [42]:
y_train_trans.astype("i")

       Score
39087      4
30893      4
45278      4
16398      4
13653      4
...      ...
11284      4
44732      0
38158      4
860        4
15795      4

[40000 rows x 1 columns]

In [43]:
y_test_trans = OE.fit_transform(y_test)

In [44]:
y_test_trans = y_test_trans.astype(int)

In [45]:
X_train_trans

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 1261569 stored elements and shape (40000, 5000)>

In [46]:
y_train_trans

       Score
39087    4.0
30893    4.0
45278    4.0
16398    4.0
13653    4.0
...      ...
11284    4.0
44732    0.0
38158    4.0
860      4.0
15795    4.0

[40000 rows x 1 columns]

In [47]:
y_train_trans = y_train_trans.astype(int)

In [48]:
y_train_trans

       Score
39087      4
30893      4
45278      4
16398      4
13653      4
...      ...
11284      4
44732      0
38158      4
860        4
15795      4

[40000 rows x 1 columns]

In [49]:
y_test_trans

       Score
33553      4
9427       4
199        3
12447      4
39489      4
...      ...
28567      4
25079      3
18707      2
15200      2
5857       4

[10000 rows x 1 columns]

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Train Logistic Regression
model = LogisticRegression(max_iter=1000, random_state=42, n_jobs=-1)
model.fit(X_train_trans, y_train)

# Predict
y_pred = model.predict(X_test_trans)

# Metrics
print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
print(f"Precision: {precision_score(y_test, y_pred, average='weighted'):.4f}")
print(f"Recall: {recall_score(y_test, y_pred, average='weighted'):.4f}")
print(f"F1-Score: {f1_score(y_test, y_pred, average='weighted'):.4f}")

print("\n" + "="*60)
print("Classification Report:")
print("="*60)
print(classification_report(y_test, y_pred))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=True)
plt.title('Confusion Matrix - Logistic Regression')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.tight_layout()
plt.show()

In [50]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Train Logistic Regression
model = LogisticRegression(max_iter=1000, random_state=42, n_jobs=-1)
model.fit(X_train_trans, y_train)

C:\Users\vishwa\.conda\envs\batch433\Lib\site-packages\sklearn\linear_model\_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)
C:\Users\vishwa\.conda\envs\batch433\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression(max_iter=1000, n_jobs=-1, random_state=42)

In [51]:
y_pred = model.predict(X_test_trans)

In [55]:
y_pred = pd.DataFrame(y_pred)

In [53]:

# Metrics
print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
print(f"Precision: {precision_score(y_test, y_pred, average='weighted'):.4f}")
print(f"Recall: {recall_score(y_test, y_pred, average='weighted'):.4f}")
print(f"F1-Score: {f1_score(y_test, y_pred, average='weighted'):.4f}")

print("\n" + "="*60)
print("Classification Report:")
print("="*60)
print(classification_report(y_test, y_pred))

Accuracy: 0.7027
Precision: 0.6707
Recall: 0.7027
F1-Score: 0.6831

============================================================
Classification Report:
============================================================
              precision    recall  f1-score   support

           1       0.60      0.58      0.59       883
           2       0.32      0.24      0.27       528
           3       0.34      0.29      0.31       740
           4       0.37      0.25      0.30      1363
           5       0.81      0.90      0.85      6486

    accuracy                           0.70     10000
   macro avg       0.49      0.45      0.47     10000
weighted avg       0.67      0.70      0.68     10000

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# ============================================================================
# TF-IDF FEATURE EXTRACTION
# ============================================================================
tfidf = TfidfVectorizer(max_features=5000)
X_train_trans2 = tfidf.fit_transform([" ".join(map(str, x)) for x in X_train["cleaned_text"]])
X_test_trans2 = tfidf.transform([" ".join(map(str, x)) for x in X_test["cleaned_text"]])

print("TF-IDF Shape:")
print(f"X_train_trans2: {X_train_trans2.shape}")
print(f"X_test_trans2: {X_test_trans2.shape}")

# ============================================================================
# LOGISTIC REGRESSION - BAG OF WORDS
# ============================================================================
print("\n" + "="*70)
print("BAG OF WORDS - LOGISTIC REGRESSION")
print("="*70)

model_bow = LogisticRegression(max_iter=1000, random_state=42, n_jobs=-1)
model_bow.fit(X_train_trans2, y_train)
y_pred_bow = model_bow.predict(X_test_trans2)

print(f"Accuracy: {accuracy_score(y_test, y_pred_bow):.4f}")
print(f"Precision: {precision_score(y_test, y_pred_bow, average='weighted'):.4f}")
print(f"Recall: {recall_score(y_test, y_pred_bow, average='weighted'):.4f}")
print(f"F1-Score: {f1_score(y_test, y_pred_bow, average='weighted'):.4f}")
print("\nClassification Report (BoW):")
print(classification_report(y_test, y_pred_bow))

# ============================================================================
# LOGISTIC REGRESSION - TF-IDF
# ============================================================================
print("\n" + "="*70)
print("TF-IDF - LOGISTIC REGRESSION")
print("="*70)

model_tfidf = LogisticRegression(max_iter=1000, random_state=42, n_jobs=-1)
model_tfidf.fit(X_train_trans2, y_train)
y_pred_tfidf = model_tfidf.predict(X_test_trans2)

print(f"Accuracy: {accuracy_score(y_test, y_pred_tfidf):.4f}")
print(f"Precision: {precision_score(y_test, y_pred_tfidf, average='weighted'):.4f}")
print(f"Recall: {recall_score(y_test, y_pred_tfidf, average='weighted'):.4f}")
print(f"F1-Score: {f1_score(y_test, y_pred_tfidf, average='weighted'):.4f}")
print("\nClassification Report (TF-IDF):")
print(classification_report(y_test, y_pred_tfidf))

# ============================================================================
# COMPARISON
# ============================================================================
print("\n" + "="*70)
print("MODEL COMPARISON")
print("="*70)

comparison = {
    'Metric': ['Accuracy', 'Precision', 'Recall', 'F1-Score'],
    'BoW': [
        accuracy_score(y_test, y_pred_bow),
        precision_score(y_test, y_pred_bow, average='weighted'),
        recall_score(y_test, y_pred_bow, average='weighted'),
        f1_score(y_test, y_pred_bow, average='weighted')
    ],
    'TF-IDF': [
        accuracy_score(y_test, y_pred_tfidf),
        precision_score(y_test, y_pred_tfidf, average='weighted'),
        recall_score(y_test, y_pred_tfidf, average='weighted'),
        f1_score(y_test, y_pred_tfidf, average='weighted')
    ]
}

import pandas as pd
comparison_df = pd.DataFrame(comparison)
print(comparison_df)

# ============================================================================
# CONFUSION MATRICES
# ============================================================================
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# BoW Confusion Matrix
cm_bow = confusion_matrix(y_test, y_pred_bow)
sns.heatmap(cm_bow, annot=True, fmt='d', cmap='Blues', ax=axes[0], cbar=True)
axes[0].set_title('Confusion Matrix - BoW')
axes[0].set_ylabel('True Label')
axes[0].set_xlabel('Predicted Label')

# TF-IDF Confusion Matrix
cm_tfidf = confusion_matrix(y_test, y_pred_tfidf)
sns.heatmap(cm_tfidf, annot=True, fmt='d', cmap='Greens', ax=axes[1], cbar=True)
axes[1].set_title('Confusion Matrix - TF-IDF')
axes[1].set_ylabel('True Label')
axes[1].set_xlabel('Predicted Label')

plt.tight_layout()
plt.savefig('bow_vs_tfidf_comparison.png', dpi=300, bbox_inches='tight')
plt.show()

print("\n✅ Models trained and compared successfully!")

TF-IDF Shape:
X_train_trans2: (40000, 5000)
X_test_trans2: (10000, 5000)

======================================================================
BAG OF WORDS - LOGISTIC REGRESSION
======================================================================

C:\Users\vishwa\.conda\envs\batch433\Lib\site-packages\sklearn\linear_model\_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)
C:\Users\vishwa\.conda\envs\batch433\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Accuracy: 0.7223
Precision: 0.6707
Recall: 0.7223
F1-Score: 0.6744

Classification Report (BoW):
              precision    recall  f1-score   support

           1       0.63      0.57      0.60       883
           2       0.48      0.12      0.19       528
           3       0.42      0.19      0.26       740
           4       0.44      0.20      0.27      1363
           5       0.77      0.96      0.86      6486

    accuracy                           0.72     10000
   macro avg       0.55      0.41      0.44     10000
weighted avg       0.67      0.72      0.67     10000


======================================================================
TF-IDF - LOGISTIC REGRESSION
======================================================================

C:\Users\vishwa\.conda\envs\batch433\Lib\site-packages\sklearn\linear_model\_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)
C:\Users\vishwa\.conda\envs\batch433\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)